services:
  backend:
    container_name: geoninja_back
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    volumes:
      - ./backend/data:/app/backend/data:ro
    depends_on:
      data_pipeline:
        condition: service_completed_successfully

  frontend:
    container_name: geoninja_front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_completed_successfully

  data_pipeline:
    container_name: geoninja_dp
    build:
      context: .
      dockerfile: data_pipeline/Dockerfile
    volumes:
      - ./:/repo
      - geoninja_dp_work:/dp_work
    environment:
      - GEONINJA_REPO_DIR=/repo
      - GEONINJA_DP_WORK_DIR=/dp_work
      - GEONINJA_RUNTIME=container
    working_dir: /repo
    command: poetry -C data_pipeline run python -m geoninja_dp.run --force

volumes:
  geoninja_dp_work:
