/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/local_params/lookup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Lookup Local Params
     * @description Resolve local parameters for a given location.
     *
     *     Request:
     *         - `location`: latitude/longitude
     *         - `keys`: list of parameter keys to resolve
     *
     *     Response:
     *         Returns one :class:`~geoninja_backend.models.local_param_lookup.ParamLookupResultItem`
     *         per requested key. Keys are processed independently; a missing value for one
     *         key does not prevent other keys from resolving.
     *
     *     Implementation notes:
     *         - Expensive lookups (GLiM/GLHYMPS/raster sampling) are performed at most once
     *           per request when any requested key depends on that dataset.
     *         - Some keys are currently hard-coded (e.g., heating/cooling period boundaries).
     */
    post: operations["lookup_local_params_api_local_params_lookup_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analysis/run": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Run Analysis
     * @description Run an analysis for the given parameters.
     *
     *     Args:
     *         req: Request model containing `location` (lat/lng) and a `params` object
     *             whose keys correspond to the parameter registry.
     *
     *     Returns:
     *         An :class:`~geoninja_backend.models.analysis_run.AnalysisRunResponse`
     *         containing the provided location, a `results` object (status + result
     *         lists), and an optional `runId`.
     */
    post: operations["run_analysis_api_analysis_run_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AnalysisResultItem
     * @description A single analysis result item.
     *
     *     Attributes:
     *         key: Stable identifier for this result.
     *         value: Numeric or string value (may be `null`).
     *         unit: Unit string (may be `null`), expected to match the contract.
     */
    AnalysisResultItem: {
      /** Key */
      key: string;
      /** Value */
      value?: number | string | null;
      /** Unit */
      unit?: string | null;
    };
    /**
     * AnalysisRunRequest
     * @description Request model for an analysis run.
     *
     *     Attributes:
     *         location: Lat/lng for contextual lookups (and for echoing in responses).
     *         params: Input parameters for the analysis. Keys correspond to the shared
     *             parameter registry.
     *         runId: Optional client-provided run identifier.
     *         startedAt: Optional client timestamp (epoch seconds or ms depending on
     *             client convention).
     *         optInputs: Optional extra inputs that may be `null` per key.
     */
    AnalysisRunRequest: {
      location: components["schemas"]["LatLng"];
      /** Params */
      params: {
        [key: string]: number | string;
      };
      /** Runid */
      runId?: number | null;
      /** Startedat */
      startedAt?: number | null;
      /** Optinputs */
      optInputs?: {
        [key: string]: number | string | null;
      } | null;
    };
    /**
     * AnalysisRunResponse
     * @description Response model for an analysis run.
     */
    AnalysisRunResponse: {
      location: components["schemas"]["LatLng"];
      results: components["schemas"]["AnalysisRunResults"];
      /** Runid */
      runId?: number | null;
    };
    /**
     * AnalysisRunResults
     * @description Results model for an analysis run.
     *
     *     Attributes:
     *         ates_kpi_results: List of KPI-type results (may be `null`).
     *         derived_quantities: List of derived-quantity results (may be `null`).
     *         status: Overall status of the computation.
     *         message: Optional human-readable context (typically present on errors).
     */
    AnalysisRunResults: {
      /** Ates Kpi Results */
      ates_kpi_results?: components["schemas"]["AnalysisResultItem"][] | null;
      /** Derived Quantities */
      derived_quantities?: components["schemas"]["AnalysisResultItem"][] | null;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "error";
      /** Message */
      message?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LatLng
     * @description Geographic coordinates.
     *
     *     This type is used in API requests/responses where a location must be
     *     provided by the client.
     *
     *     Attributes:
     *         lat: Latitude in decimal degrees.
     *         lng: Longitude in decimal degrees.
     */
    LatLng: {
      /** Lat */
      lat: number;
      /** Lng */
      lng: number;
    };
    /**
     * ParamLookupRequest
     * @description Request payload for local parameter lookup.
     *
     *     Attributes:
     *         location:
     *             Latitude/longitude at which to resolve local parameters.
     *
     *         keys:
     *             Parameter keys to resolve. Must contain at least one key.
     *
     *         inputs:
     *             Optional additional inputs that can influence lookup behaviour.
     *
     *             Currently, the following global input is supported:
     *
     *             - ``year`` (int):
     *                 Reference year used for year-dependent lookups such as
     *                 heating/cooling period segmentation (e.g. ``heatPeriodStart``,
     *                 ``coolPeriodEnd``). If any year-dependent keys are requested,
     *                 ``inputs["year"]`` must be provided.
     */
    ParamLookupRequest: {
      location: components["schemas"]["LatLng"];
      /** Keys */
      keys: string[];
      /** Inputs */
      inputs?: {
        [key: string]: number | string | null;
      } | null;
    };
    /**
     * ParamLookupResponse
     * @description Response payload for local parameter lookup.
     */
    ParamLookupResponse: {
      location: components["schemas"]["LatLng"];
      /** Results */
      results: components["schemas"]["ParamLookupResultItem"][];
    };
    /**
     * ParamLookupResultItem
     * @description Result for a single requested key.
     */
    ParamLookupResultItem: {
      /** Key */
      key: string;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "missing" | "unsupported" | "error";
      /** Value */
      value?: number | string | null;
      /** Message */
      message?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  lookup_local_params_api_local_params_lookup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ParamLookupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ParamLookupResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  run_analysis_api_analysis_run_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalysisRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
